# PostgreSQL. Versions 9.3 and up are supported.
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: scimiam_development

test:
  <<: *default
  database: scimiam_test

production:
  <<: *default
  database: scimiam_production
  username: scimiam
  host: <%= ENV['DB_HOST'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
