name: Build docker image
on:
  push:

jobs:
    set_build_id:
        runs-on: ["self-hosted", "k8s-prod"]
        steps:
        - name: Generate build ID
          id: prep
          run: |
            branch=${GITHUB_REF##*/}
            sha=${GITHUB_SHA::8}
            run_number=${GITHUB_RUN_NUMBER}
            echo "BUILD_ID=${branch}-${sha}-${run_number}" >> $GITHUB_OUTPUT
        outputs:
            build_id: ${{ steps.prep.outputs.BUILD_ID }}
    build:
        runs-on: ["self-hosted", "k8s-prod"]
        needs: set_build_id
        steps:
        - uses: actions/checkout@v4
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
          with:
            driver-opts: |
              network=host
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            network: host
            push: true
            tags: neonlabsorg/scimiam:${{ needs.set_build_id.outputs.build_id }}